// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.GraphQL.Client")>]
[<assembly: AssemblyProductAttribute("Pure.GraphQL")>]
[<assembly: AssemblyDescriptionAttribute("FSharp implementation of Facebook GraphQL query language")>]
[<assembly: AssemblyVersionAttribute("1.0.2")>]
[<assembly: AssemblyFileVersionAttribute("1.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.GraphQL.Client"
    let [<Literal>] AssemblyProduct = "Pure.GraphQL"
    let [<Literal>] AssemblyDescription = "FSharp implementation of Facebook GraphQL query language"
    let [<Literal>] AssemblyVersion = "1.0.2"
    let [<Literal>] AssemblyFileVersion = "1.0.2"
