// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Pure.GraphQL.Shared")>]
[<assembly: AssemblyProductAttribute("Pure.GraphQL")>]
[<assembly: AssemblyDescriptionAttribute("FSharp implementation of Facebook GraphQL query language")>]
[<assembly: AssemblyVersionAttribute("1.0.2")>]
[<assembly: AssemblyFileVersionAttribute("1.0.2")>]
[<assembly: InternalsVisibleToAttribute("Pure.GraphQL.Server")>]
[<assembly: InternalsVisibleToAttribute("Pure.GraphQL.Client")>]
[<assembly: InternalsVisibleToAttribute("Pure.GraphQL.Client.DesignTime")>]
[<assembly: InternalsVisibleToAttribute("Pure.GraphQL.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Pure.GraphQL.Shared"
    let [<Literal>] AssemblyProduct = "Pure.GraphQL"
    let [<Literal>] AssemblyDescription = "FSharp implementation of Facebook GraphQL query language"
    let [<Literal>] AssemblyVersion = "1.0.2"
    let [<Literal>] AssemblyFileVersion = "1.0.2"
    let [<Literal>] InternalsVisibleTo = "Pure.GraphQL.Server"
    let [<Literal>] InternalsVisibleTo_1 = "Pure.GraphQL.Client"
    let [<Literal>] InternalsVisibleTo_2 = "Pure.GraphQL.Client.DesignTime"
    let [<Literal>] InternalsVisibleTo_3 = "Pure.GraphQL.Tests"
